steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo $DATABASE_URL
      docker build \
        -t europe-southwest1-docker.pkg.dev/fh-nest-microservices/image-registtry/orders-microservice \
        -f dockerfile.prod \
        --platform=linux/amd64 \
        --build-arg ORDERS_DATABASE_URL=$DATABASE_URL \
        .

  secretEnv: ['DATABASE_URL']

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      "push",
      "europe-southwest1-docker.pkg.dev/fh-nest-microservices/image-registtry/orders-microservice",
    ]

availableSecrets:
  secretManager:
  - versionName: projects/856186106369/secrets/orders_database_url/versions/1
    env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY
